### ISSUE TITLE
在2.12.0版本中如果打开热词更新会出现 java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory异常，导致服务启动失败。

### ISSUE THREAD

**Issue by liuwenbo200285** [aparo/opensearch-analysis-ik#32]
[2024-03-08T02:52:19,657][INFO ][o.w.a.d.Dictionary       ] [opensearch-node2] [Dict Loading] http://xx.xx.xx/opensearch/ik/ext_dict/customDict.dic
opensearch-node2       | [2024-03-08T02:52:19,699][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [opensearch-node2] fatal error in thread [opensearch[opensearch-node2][clusterApplierService#updateTask][T#1]], exiting
opensearch-node2       | java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
opensearch-node2       | 	at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82) ~[?:?]
opensearch-node2       | 	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:970) ~[?:?]
opensearch-node2       | 	at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56) ~[?:?]

**Comment by ijustloveses** [comment]
同样的问题，opensearch 2.13
